// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACj_69KaXUvfeP6wDswt1d2UMlt0jhcg8',
    appId: '1:1002465098657:web:e445a2f58059dc903369e0',
    messagingSenderId: '1002465098657',
    projectId: 'smart-search-984a7',
    authDomain: 'smart-search-984a7.firebaseapp.com',
    storageBucket: 'smart-search-984a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNPKMlT1ia4BlxJMpl2NSSPlRxnfIoc0Y',
    appId: '1:1002465098657:android:5235c7f10bc9ac283369e0',
    messagingSenderId: '1002465098657',
    projectId: 'smart-search-984a7',
    storageBucket: 'smart-search-984a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5rX8V2tJL4LVDaMtpHfsTZ1tBoEXK8rI',
    appId: '1:1002465098657:ios:d867c6093161189e3369e0',
    messagingSenderId: '1002465098657',
    projectId: 'smart-search-984a7',
    storageBucket: 'smart-search-984a7.firebasestorage.app',
    iosBundleId: 'com.example.smartDocumentSearchFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5rX8V2tJL4LVDaMtpHfsTZ1tBoEXK8rI',
    appId: '1:1002465098657:ios:d867c6093161189e3369e0',
    messagingSenderId: '1002465098657',
    projectId: 'smart-search-984a7',
    storageBucket: 'smart-search-984a7.firebasestorage.app',
    iosBundleId: 'com.example.smartDocumentSearchFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACj_69KaXUvfeP6wDswt1d2UMlt0jhcg8',
    appId: '1:1002465098657:web:f13a4c4ee1095e813369e0',
    messagingSenderId: '1002465098657',
    projectId: 'smart-search-984a7',
    authDomain: 'smart-search-984a7.firebaseapp.com',
    storageBucket: 'smart-search-984a7.firebasestorage.app',
  );
}